on: push
name: Build & Test
env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ex${{matrix.elixir}}/OTP${{matrix.otp}}
    strategy:
      matrix:
        elixir: ["1.18.4", "1.19.0-rc.0"]
        otp: ["27.3.4", "28.0"]
        exclude:
          - elixir: "1.15.8"
            otp: "27.2.4"
          - elixir: "1.16.3"
            otp: "27.2.4"
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - run: mix test
